### ISSUE TITLE
377 BA.2 samples in Japan with S:R493Q,S:F486V,S:L452R

### ISSUE THREAD

**Issue by jmcbroome** [jmcbroome/auto-pango-designation#131]
BA.2.0 is a proposed sublineage of BA.2 that includes 377 samples.

It was identified from the tree file gisaidAndPublic.2022-10-02.proposed.pb as the descendents of node_1806084.

The earliest dated sample was found on 2022-06-07.

The latest dated sample was found on 2022-09-26.

It is found in 20 countries, most commonly Japan where 71.00% of its samples were sequenced.

BA.2.0 has a Bloom Lab escape score of 0.45, -0.19 over the parent lineage.

It is defined by the following spike protein changes: S:R493Q,S:F486V,S:L452R. There are 38 defining protein changes overall.

NOTE: The following links search by genotype and parent lineage; they may additionally highlight samples outside of the proposed clade that convergently evolved the same mutations or that were added after this lineage was inferred, 
or not display or highlight samples which reverted some of the key changes or were removed after this lineage was inferred. They may also take a moment to complete the search on loading.

View it on [cov-spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.2%2A%26%5B39-of%3AG28681T%2C+A27683G%2C+G27583A%2C+C27732T%2C+A27726T%2C+T27587C%2C+A27520G%2C+G27517A%2C+C27725T%2C+T23018G%2C+A27528T%2C+T27728C%2C+G27518A%2C+C1931A%2C+T27531C%2C+C27519T%2C+A27723T%2C+C27590T%2C+C27577T%2C+C27689T%2C+C27526A%2C+C2790T%2C+C27686T%2C+A27691G%2C+C27889T%2C+T27693C%2C+A27749G%2C+T22917G%2C+C27688T%2C+T28693C%2C+T27692C%2C+C27524G%2C+C27735T%2C+C27575A%2C+G26529A%2C+G27589A%2C+A27721G%2C+G12160A%2C+T27582G%5D)

View it on [taxonium](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BA.2%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BA.2%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%222790%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227689%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227688%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%224ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227692%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%225ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227582%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%226ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227577%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%227ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227583%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%228ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227587%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%229ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227589%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2210ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227590%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2211ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227693%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2212ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227517%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2213ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227518%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2214ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227519%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2215ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227520%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2216ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227524%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2217ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227526%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2218ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227528%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2219ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227514%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2220ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227683%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227686%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227691%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%229866%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2224ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227383%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2225ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227384%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2226ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2212160%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2227ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2223040%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2228ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2226529%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2229ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2226858%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2230ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227259%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2231ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227889%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2232ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2228681%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2233ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2228693%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2234ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%221931%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2235ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227382%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2236ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227514%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2237ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227531%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2238ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227575%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2239ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227721%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2240ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227723%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2241ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227725%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2242ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227726%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2243ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227728%22%2C%22new_residue%22%3A%22C%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2244ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227732%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2245ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227735%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2246ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2227749%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2247ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2223018%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%2248ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2222917%22%2C%22new_residue%22%3A%22G%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)

The following samples are included in this proposal: 
Japan/PG-342077/2022|EPI_ISL_14879737|2022-08-13
Japan/PG-333892/2022|EPI_ISL_14645939|2022-08-03
Japan/PG-283146/2022|EPI_ISL_14344740|2022-07-16
Israel/SMC-7090348/2022|EPI_ISL_13961806|2022-07-10
Japan/PG-333343/2022|EPI_ISL_14645431|2022-08-01
Japan/PG-353417/2022|EPI_ISL_15082771|2022-08-29
Japan/PG-355914/2022|EPI_ISL_15082839|2022-08-31
Japan/PG-267480/2022|EPI_ISL_14125831|2022-06-27
Japan/PG-288792/2022|EPI_ISL_14351077|2022-07-23
Japan/PG-355710/2022|EPI_ISL_15167549|2022-09-09
Japan/PG-340217/2022|EPI_ISL_14876966|2022-08-20
Japan/PG-279237/2022|EPI_ISL_14340555|2022-07-13
Denmark/DCGC-567339/2022|OX326293.1|2022-08-16
Japan/PG-278796/2022|EPI_ISL_14340143|2022-07-19
USA/GA-CDC-LC0841641/2022|OP332885.1|2022-08-15
As well as 362 additional samples.

**Comment by jmcbroome** [comment]
This particular lineage stands out from the crowd, as being a large group of samples seemingly descended from a long branch with a ton of amino acid changes. Unfortunately, there are so many (and so many samples are GISAID only) that the links to taxonium and cov-spectrum are nonfunctional.

[Quick Nextstrain JSON of this clade with some context](https://github.com/jmcbroome/auto-pango-designation/files/9703046/weirdclade.json.zip)

Particularly interested to garner thoughts on this one. Legitimate? Possible successful recombinant, strange pattern of bad data, or just a flat out bug in the pipeline?

**Comment by chrisruis** [comment]
I suspect these are BA.5.3.1 sequences that have been misplaced within BA.2

There are several long branches leading to these sequences. All of the mutations on those long branches appear to be within Orf7a. The sequences within this clade have missing data for a lot of Orf7a so those long branches are likely all artifactual mutations

Looking at the mutations on non-long branches that separate these sequences from BA.2, they were either acquired by the BA.5 common ancestor (Orf1a:3201L, Orf6:61D, M:3N, S:452R, S:486V, S:493Q, 27889T) or are acquired leading to BA.5.3 (Orf1a:556K) or leading to BA.5.3.1 (N:136D). They therefore seem to have the mutations expected of BA.5.3.1 so seem likely to be BA.5.3.1 sequences that have been misplaced

**Comment by AngieHinrichs** [comment]
Good spot Chris!  Yes, this is definitely a problematic branch and that cluster is out of place in BA.2.  Here's a taxonium view (black circled node is the root of this proposed cluster):
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/186983/195150607-68bd5ee3-aac3-470b-ae53-04d238a7fd4e.png">

My guess is that there are a few sequences that have a lot of spurious substitutions in ORF7a (27500's), and then sequences that have mostly Ns in those regions got pulled in.  The `matUtils extract --max-mutation-density` filtering that I recently added would probably trim most of the fluff and leave the tight cluster at the end -- but unfortunately it would leave it in its current position in BA.2, and the Ns would still be imputed as the spurious substitutions so even optimizing might not correctly place it in BA.5.3 although I haven't tried that.

**Comment by jmcbroome** [comment]
Yes, I see. Thank you for the explanation- I'll be looking into applying the max mutation density filtering today (as well as the reversion filtering from node_stats) and making a fresh batch of issues. I'll have to think about the best way to handle groups like this. It's possible to put a maximum distance threshold so we can ignore lineage proposals that are *too* distinct from the ancestral for being possible bad data, but that means that we might miss a new omicron situation! Maybe include them, but flag them somehow? Something to think about. For now, I'm going to try applying the mutational density filtering and see how things come out.
