### ISSUE TITLE
752 BA.5.1.22 samples in France

### ISSUE THREAD

**Issue by jmcbroome** [jmcbroome/auto-pango-designation#170]
BA.5.1.22.0 is a proposed sublineage of BA.5.1.22 that includes 752 samples.

It was identified from the tree file gisaidAndPublic.2022-10-11.proposed.pb as the descendents of node_1921649.

The earliest dated sample was found on 2021-11-15.

The latest dated sample was found on 2022-09-29.

It is found in 39 countries, most commonly France where 37.00% of its samples were sequenced.

BA.5.1.22.0 has a Bloom Lab escape score of 0.45, unchanged from the parent lineage.

Full mutational path from the ancestral lineage to the proposed sublineage: C6582T>C24082T>G6671A

Full amino acid change path from the ancestral lineage to the proposed sublineage: ORF1ab:T2106I>>ORF1ab:D2136N

NOTE: The following links search by genotype and parent lineage; they may additionally highlight samples outside of the proposed clade that convergently evolved the same mutations or that were added after this lineage was inferred, 
or not display or highlight samples which reverted some of the key changes or were removed after this lineage was inferred. They may also take a moment to complete the search on loading.

View it on [cov-spectrum](https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=nextcladePangoLineage%3ABA.5.1.22%2A%26%5B3-of%3AC24082T%2C+C6582T%2C+G6671A%5D)

View it on [taxonium](https://taxonium.org/?backend=https://api.cov2tree.org&srch=%5B%7B%22key%22%3A%22aa1%22%2C%22type%22%3A%22boolean%22%2C%22method%22%3A%22boolean%22%2C%22text%22%3A%22BA.5.1.22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%2C%22subspecs%22%3A%5B%7B%22key%22%3A%22ab0%22%2C%22type%22%3A%22meta_pango_lineage_usher%22%2C%22method%22%3A%22text_exact%22%2C%22text%22%3A%22BA.5.1.22%22%2C%22gene%22%3A%22S%22%2C%22position%22%3A484%2C%22new_residue%22%3A%22any%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%221ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%226582%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%222ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%2224082%22%2C%22new_residue%22%3A%22T%22%2C%22min_tips%22%3A0%7D%2C%7B%22key%22%3A%223ab%22%2C%22type%22%3A%22genotype%22%2C%22method%22%3A%22genotype%22%2C%22text%22%3A%22%22%2C%22gene%22%3A%22nt%22%2C%22position%22%3A%226671%22%2C%22new_residue%22%3A%22A%22%2C%22min_tips%22%3A0%7D%5D%2C%22boolean_method%22%3A%22and%22%7D%5D&enabled=%7B%22aa1%22%3A%22true%22%7D&zoomToSearch=0)

The following samples are included in this proposal: 
France/IDF-IPP43960/2022|EPI_ISL_13994048|2022-07-04
Denmark/DCGC-564677/2022|OX325148.1|2022-08-09
France/NAQ-cerba-22Q0175435/2022|EPI_ISL_14332902|2022-06-20
France/PDL-IPP45890/2022|EPI_ISL_14135419|2022-07-18
France/PDL-IPP42771/2022|EPI_ISL_13873754|2022-06-27
France/HDF-IPP43070/2022|EPI_ISL_13874165|2022-06-27
France/ARA-GENBIO-14291602595/2022|EPI_ISL_13326264|2022-06-09
Denmark/DCGC-568564/2022|OX325931.1|2022-08-14
Israel/CVL-8009786/2022|EPI_ISL_14468295|2022-07-27
Japan/TKYkbm40650/2022|EPI_ISL_14720949|2022-07-15
USA/MA-CDCBI-CRSP_SH2JA7I4OQITVQDQ/2022|OP426184.1|2022-08-29
USA/CT-CDC-LC0787778/2022|OP109123.1|2022-07-12
Belgium/IPG-1861/2022|EPI_ISL_14995597|2022-08-22
Japan/TKYnat4858/2022|EPI_ISL_14510185|2022-07-16
Netherlands/FR-RIVM-112122/2022|EPI_ISL_15177658|2022-09-05
As well as 737 additional samples.

**Comment by corneliusroemer** [comment]
Also quite dead, and a bit small to designate it just for stamp collecting?

I'm fine with labelling large chunks of dead parts of the tree, but the lineages should then be more like 10-100k instead of <1k in size, otherwise we'll end up with 10k lineages in no time 🙃 

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/25161793/195800545-f10d100d-b309-4f31-83cd-42329c1f4442.png">
