### ISSUE TITLE
ENH: Add AA mutations to issue title

### ISSUE THREAD

**Issue by corneliusroemer** [jmcbroome/auto-pango-designation#175]

**Comment by corneliusroemer** [comment]
Oh I see, you only include Spike at the moment, makes sense!

What about listing all Spike substitutions and some (maybe the last or first N of the non-Spike)?

https://github.com/jmcbroome/auto-pango-designation/issues/167

**Comment by jmcbroome** [comment]
I've iterated a lot on issue titles and body content inclusion- I can easily make this change! Thank you for the feedback

**Comment by corneliusroemer** [comment]
Around 2 mutations would be great always, as that allows skimming more easily :)
